### ISSUE TITLE
[Request] Draw clear/undo button

### ISSUE THREAD

**Issue by tpalinski** [annazhurba/przetw_rospr_projekt#4]
### Request
A button that would undo/c;ear all the drawings present on the page.

### Motivation
If the user makes a mistake or if they want to start over, there is currently no way of reverting their work to its previous state. Such feature would enhance UX.

**Comment by annazhurba** [comment]
I have added the clear button, so you may check it out :)

**Comment by tpalinski** [comment]
Works great, thanks!
